services:
  db:
    image: postgres:16-alpine
    container_name: blog-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - blog-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-net

  backend:
    image: 206492233485.dkr.ecr.eu-west-2.amazonaws.com/assimetria/blog-backend:latest
    container_name: blog-backend
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      AI_API_KEY: ${AI_API_KEY}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-net

  frontend:
    image: 206492233485.dkr.ecr.eu-west-2.amazonaws.com/assimetria/blog-frontend:latest
    container_name: blog-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:

volumes:
  blog-data:
